server:
  port: 80

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.luojin.zuul: debug
zuul:
  routes:
    user-route:
      path: /apptest/*,/feign/*
      service-id: apptest,feign
