server:
  port: 8889

spring:
  application:
    name: apptest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  config: classpath:logback-spring.xml
  level:
    org.luojin.apptest: debug
