server:
  port: 8084

spring:
  application:
    name: message
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        max-concurrency: 1
        concurrency: 1
        retry:
          enabled: true
    publisher-returns: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  config: classpath:config/logback-spring.xml
  level:
    org.luojin.message: debug

