server:
  port: 8084

spring:
  application:
    name: message
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
    listener:
      direct:
        acknowledge-mode: manual

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  config: classpath:config/logback-spring.xml
  level:
    org.luojin.message: debug

