server:
  port: 8084

spring:
  application:
    name: message
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        max-concurrency: 1
        concurrency: 1
        retry:
          enabled: true
        acknowledge-mode: manual  #手动模式必须开启保证消息不丢失
    publisher-returns: true
  mail:
    host: smtp.qq.com
    username: 742411332@qq.com
    password: jsycvwqhjiyxbfjh
    default-encoding: utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  config: classpath:config/logback-spring.xml
  level:
    org.springframework.amqp.rabbit: error
    org.luojin.message: debug

