server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        id: feign
        uri: http://localhost:8091
        predicates:
          Path=/feign/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    #将实例信息变更同步到 Eureka Server的初始延迟时间
    initial-instance-info-replication-interval-seconds: 5
    #拉取注册信息缓存更新时间间隔
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #服务续期时间
logging:
  level:
    root: debug