server:
  port: 8083

spring:
  application:
    name: mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  config: classpath:config/logback-spring.xml
  level:
    org.luojin.mq: debug

